# Generated by Django 4.2.1 on 2023-06-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_basket_product_alter_basket_user_wishlist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
