# Generated by Django 4.2.1 on 2023-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
